In [ ]:
!pip install transformers sentence-transformers torch scikit-learn Sastrawi nltk protobuf sentencepiece pandas

import os
import json
import re
import numpy as np
import torch
import logging
import pandas as pd
from dataclasses import dataclass
from typing import List, Dict, Optional
from pathlib import Path
import nltk
nltk.download('punkt')
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import sent_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import AgglomerativeClustering
from transformers import AutoTokenizer,AutoModel, AutoModelForSeq2SeqLM, MBartTokenizer, BertTokenizer
from sentence_transformers import SentenceTransformer
from google.colab import drive

logging.basicConfig(level=logging.INFO, format='%(message)s')
logger = logging.getLogger()

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (5.29.6)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 5.5 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
class TextPreprocessor:
    def __init__(self):
        factory = StemmerFactory()
        self.stemmer = factory.create_stemmer()

    def clean_text_display(self, text: str) -> str:
        # PEMBERSIHAN KHUSUS TAMPILAN

        remove = [r'^liputan6\.com\s*(?:-|:)\s*',r'^(?:liputan6\.com|com)\s*,\s*[a-z\s]+\s*(?:-|:)\s*',r'BACA JUGA:.*?(?=\n|$)', r'Disclaimer:.*?(?=\n|$)', r'^\s*ADVERTISEMENT.*?(?=\n|$)',
                  r'Perbesar', r'Selengkapnya', r'\d+\s+dari\s+\d+\s+halaman', r'\s*\([A-Za-z0-9/\.\s-]+\)\.?\s*$']
        for p in remove: text = re.sub(p, ' ', text, flags=re.IGNORECASE|re.DOTALL)

        # Fix Spasi Gancet
        text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)
        text = re.sub(r'([A-Z])([A-Z][a-z])', r'\1 \2', text)
        text = re.sub(r'([.,!?])(?=[a-zA-Z])', r'\1 ', text)
        text = re.sub(r'([a-zA-Z])(\d)', r'\1 \2', text)
        text = re.sub(r'(\d)([a-zA-Z])', r'\1 \2', text)
        text = text.encode('ascii', 'ignore').decode('ascii')

        return re.sub(r'\s+', ' ', text).strip()

    def case_folding_and_remove_artifacts(self, text: str) -> str:
        # TAHAP 3 & 4: CASE FOLDING & CLEANING KOMPUTASI
        text = text.lower()
        text = re.sub(r'http\S+|www\.\S+', '', text)
        text = re.sub(r'[^a-z\s]', '', text)
        return re.sub(r'\s+', ' ', text).strip()

    def split_sentences(self, text: str) -> List[str]:
        try: return sent_tokenize(text)
        except: return re.split(r'(?<=[.!?])\s+', text)

In [ ]:
class SentenceBERTEmbedder:
    """
    Sentence-BERT (SBERT) paraphrase-multilingual-MiniLM-L12-v2 (Support Bahasa Indonesia)
    """
    def __init__(self, model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"):
        print(f"   [Model] Loading Sentence-BERT ({model_name})...")
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        try:
            self.model = SentenceTransformer(model_name, device=str(self.device))
        except Exception as e:
            print(f"  Gagal load SBERT: {e}")
            raise

    def get_embeddings(self, sentences: List[str]):
        if not sentences: return np.array([])
        embeddings = self.model.encode(sentences, convert_to_numpy=True, show_progress_bar=False)
        return embeddings

In [ ]:
# import numpy as np
# import pandas as pd
# from dataclasses import dataclass
# from typing import List, Optional

# @dataclass
# class Article:
#     url: str; title: str; content: str; category: str
#     date: Optional[str] = None; author: Optional[str] = None; tags: List[str] = None

# class MMRSelector:
#     def __init__(self, lambda_param=0.7):
#         self.lambda_param = lambda_param

#     def _cosine_similarity(self, A, B):
#         """
#         Rumus: (A . B) / (||A|| * ||B||)
#         """
#         dot_product = np.dot(A, B.T)
#         norm_a = np.linalg.norm(A, axis=1, keepdims=True)
#         norm_b = np.linalg.norm(B, axis=1, keepdims=True)
#         denominator = np.dot(norm_a, norm_b.T) + 1e-10
#         return dot_product / denominator

#     def select_with_logs(self, sentences_data, embs, query, n=5):
#         if not sentences_data: return [], [], []

#         embs = np.array(embs)
#         query = np.array(query)
#         if query.ndim == 1: query = query.reshape(1, -1)
#         if embs.ndim == 1: embs = embs.reshape(1, -1)

#         # 1. HITUNG RELEVANSI MURNI (SIM_1)
#         sim_to_query = self._cosine_similarity(embs, query).flatten()
#         raw_sim_to_query = sim_to_query.copy()

#         heuristic_logs = []

#         # 2. MODIFIKASI HEURISTIK (STATE TRACKER + 50% & 30% BOOST)
#         doc_quote_state = {}

#         for i, item in enumerate(sentences_data):
#             text = item['text'].lower() if isinstance(item, dict) else str(item).lower()

#             # Ambil identitas dokumen & urutan kalimatnya
#             doc_id = item.get('doc_id', 'unknown')
#             sent_id = item.get('sent_id', i)

#             if doc_id not in doc_quote_state:
#                 doc_quote_state[doc_id] = False

#             was_in_quote = doc_quote_state[doc_id]

#             straight_quotes = text.count('"')
#             has_curly_open = '“' in text
#             has_curly_close = '”' in text

#             rule_notes = []
#             multiplier = 1.0

#             # Quote Penalty Tracker
#             is_penalized = was_in_quote or (straight_quotes > 0) or has_curly_open or has_curly_close

#             if is_penalized:
#                 multiplier *= 0.70
#                 rule_notes.append("Quote Penalty (*0.70)")

#             # Update State Kutipan
#             if has_curly_open and not has_curly_close:
#                 doc_quote_state[doc_id] = True
#             elif has_curly_close and not has_curly_open:
#                 doc_quote_state[doc_id] = False
#             elif straight_quotes % 2 != 0:
#                 doc_quote_state[doc_id] = not doc_quote_state[doc_id]

#             # Position Boost 50% dan 30%
#             if sent_id == 1:
#                 multiplier *= 1.3
#                 rule_notes.append("Position Boost 2 (*1.30)")

#             sim_to_query[i] *= multiplier
#             applied_rule = " + ".join(rule_notes) if rule_notes else "Normal"

#             heuristic_logs.append({
#                 "Doc ID": doc_id,
#                 "Sent ID": sent_id,
#                 "Raw Sim_1": float(raw_sim_to_query[i]),
#                 "Multiplier": multiplier,
#                 "Modified Sim_1": float(sim_to_query[i]),
#                 "Rule Applied": applied_rule,
#                 "Text Snippet": text[:1000]
#             })

#         sel_idx = []
#         rem_idx = list(range(len(sentences_data)))
#         logs = []

#         # 3. LOOP MMR
#         while len(sel_idx) < n and rem_idx:
#             step_candidates = []

#             if sel_idx:
#                 selected_vecs = embs[sel_idx]

#             for i in rem_idx:
#                 rel = sim_to_query[i]
#                 div = 0.0
#                 if sel_idx:
#                     curr_vec = embs[i].reshape(1, -1)
#                     sim_to_selected = self._cosine_similarity(curr_vec, selected_vecs)
#                     div = np.max(sim_to_selected)

#                 score = self.lambda_param * rel - (1 - self.lambda_param) * div

#                 step_candidates.append({
#                     "idx": i, "score": score, "rel": rel, "div": div
#                 })

#             best = max(step_candidates, key=lambda x: x['score'])

#             sel_idx.append(best['idx'])
#             rem_idx.remove(best['idx'])
#             s = sentences_data[best['idx']]

#             doc_id = s.get('doc_id', '?')
#             sent_id = s.get('sent_id', '?')
#             source_str = f"[doc_{doc_id}, sent_{sent_id}]"

#             logs.append({
#                 "Step": len(sel_idx),
#                 "Source": source_str,
#                 "MMR Score": float(best['score']),
#                 "Modified Sim_1 (Rel)": float(best['rel']),
#                 "Diversity": float(best['div']),
#                 "Text": s['text'][:1000]
#             })

#         # sel_idx
#         selected_final = [sentences_data[i] for i in sel_idx]

#         return selected_final, logs, heuristic_logs

In [ ]:
import numpy as np
import pandas as pd
from dataclasses import dataclass
from typing import List, Optional

class Article:
    url: str; title: str; content: str; category: str
    date: Optional[str] = None; author: Optional[str] = None; tags: List[str] = None

class MMRSelector:
    def __init__(self, lambda_param=0.7):
        self.lambda_param = lambda_param

    def _cosine_similarity(self, A, B):
        """
        Rumus: (A . B) / (||A|| * ||B||)
        """
        dot_product = np.dot(A, B.T)
        norm_a = np.linalg.norm(A, axis=1, keepdims=True)
        norm_b = np.linalg.norm(B, axis=1, keepdims=True)
        denominator = np.dot(norm_a, norm_b.T) + 1e-10
        return dot_product / denominator

    def select_with_logs(self, sentences_data, embs, query, n=5):
        if not sentences_data: return [], [], []

        embs = np.array(embs)
        query = np.array(query)
        if query.ndim == 1: query = query.reshape(1, -1)
        if embs.ndim == 1: embs = embs.reshape(1, -1)

        # 1. HITUNG RELEVANSI MURNI (SIM_1)
        sim_to_query = self._cosine_similarity(embs, query).flatten()

        heuristic_logs = []

        # 2. LOGGING BASELINE (Tanpa Modifikasi Heuristik)
        for i, item in enumerate(sentences_data):
            text = item['text'].lower() if isinstance(item, dict) else str(item).lower()

            # Ambil identitas dokumen & urutan kalimatnya
            doc_id = item.get('doc_id', 'unknown')
            sent_id = item.get('sent_id', i)

            # BASELINE: Multiplier selalu 1.0 (Skor murni SBERT)
            multiplier = 1.0

            heuristic_logs.append({
                "Doc ID": doc_id,
                "Sent ID": sent_id,
                "Raw Sim_1": float(sim_to_query[i]),
                "Multiplier": multiplier,
                "Modified Sim_1": float(sim_to_query[i]),
                "Rule Applied": "Baseline (Normal)",
                "Text Snippet": text[:1000]
            })

        sel_idx = []
        rem_idx = list(range(len(sentences_data)))
        logs = []

        # 3. LOOP MMR
        while len(sel_idx) < n and rem_idx:
            step_candidates = []

            if sel_idx:
                selected_vecs = embs[sel_idx]

            for i in rem_idx:
                rel = sim_to_query[i]
                div = 0.0
                if sel_idx:
                    curr_vec = embs[i].reshape(1, -1)
                    sim_to_selected = self._cosine_similarity(curr_vec, selected_vecs)
                    div = np.max(sim_to_selected)

                score = self.lambda_param * rel - (1 - self.lambda_param) * div

                step_candidates.append({
                    "idx": i, "score": score, "rel": rel, "div": div
                })

            best = max(step_candidates, key=lambda x: x['score'])

            sel_idx.append(best['idx'])
            rem_idx.remove(best['idx'])
            s = sentences_data[best['idx']]

            doc_id = s.get('doc_id', '?')
            sent_id = s.get('sent_id', '?')
            source_str = f"[doc_{doc_id}, sent_{sent_id}]"

            logs.append({
                "Step": len(sel_idx),
                "Source": source_str,
                "MMR Score": float(best['score']),
                "Modified Sim_1 (Rel)": float(best['rel']),
                "Diversity": float(best['div']),
                "Text": s['text'][:1000]
            })

        # sel_idx.sort()
        selected_final = [sentences_data[i] for i in sel_idx]

        return selected_final, logs, heuristic_logs

In [ ]:
print("⏳ Menginisialisasi Model...")
preprocessor = TextPreprocessor()
embedder = SentenceBERTEmbedder()
mmr = MMRSelector()
vectorizer = TfidfVectorizer(max_features=1000)
print(" Model Siap.\n")

⏳ Menginisialisasi Model...
   [Model] Loading Sentence-BERT (sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2)...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

 Model Siap.

In [ ]:
import os
import shutil
from google.colab import drive

os.system('fusermount -uz /content/drive')

if os.path.isdir('/content/drive') and os.listdir('/content/drive'):
    print("Warning: /content/drive still contains files after fusermount. Attempting to force clear.")
    try:
        shutil.rmtree('/content/drive')
        os.makedirs('/content/drive')
        print("/content/drive successfully removed and recreated.")
    except Exception as e:
        print(f"Error forcibly clearing /content/drive: {e}")

drive.mount('/content/drive', force_remount=True)

RAW_DATA_PATH = "/content/drive/MyDrive/Skripsi-Multi-Documents-Summary/data/raw/liputan6"
CATEGORY = "tekno" # custom kategori
CLUSTERING_THRESHOLD = 0.8

Mounted at /content/drive

In [ ]:
import pandas as pd

print("\nLoad judul artikel")
cat_dir = os.path.join(RAW_DATA_PATH, CATEGORY)
articles, raw_docs = [], []

if os.path.exists(cat_dir):
    for f in os.listdir(cat_dir):
        if f.endswith('.json'):
            try:
                d = json.load(open(os.path.join(cat_dir, f)))
                feat = f"{d['title']} {d['title']} {d.get('content','')[:500]}"
                articles.append(feat)
                raw_docs.append(d)
            except Exception as e:
                print(f"Skipping error file {f}: {e}")

if not articles: print("Data kosong"); exit()

Load judul artikel

In [ ]:
vecs = vectorizer.fit_transform(articles).toarray()

In [ ]:
# 2. CLUSTERING
clusterer = AgglomerativeClustering(
    n_clusters=None,
    metric='cosine',
    linkage='average',
    distance_threshold=CLUSTERING_THRESHOLD
)
labels = clusterer.fit_predict(vecs)

In [ ]:
# 3. GROUPING
clusters_dict = {}
for i, lbl in enumerate(labels):
    if lbl not in clusters_dict: clusters_dict[lbl] = []
    clusters_dict[lbl].append(raw_docs[i])

In [ ]:
#visualisasi cluster
print("PENGELOMPOKAN DOKUMEN (CLUSTERING)")
print("="*80)

clusters_list = []
valid_idx_counter = 0

sorted_lbls = sorted(clusters_dict.keys())
for lbl in sorted_lbls:
    docs = clusters_dict[lbl]
    is_valid = len(docs) >= 2

    if is_valid:
        status_icon = "VALID"
        clusters_list.append(docs)

        current_list_index = valid_idx_counter
        valid_idx_counter += 1

        index_msg = f"TARGET_INDEX = {current_list_index}"
    else:
        status_icon = "SKIP (Artikel < 2)"
        index_msg = "(Tidak masuk list analisis)"

    # Visualisasi Header
    status_icon = " VALID (Proses ke Summarization)" if is_valid else " SKIP (Artikel Tunggal/Kurang)"
    print(f"\n CLUSTER ID: {lbl}")
    print(f"   STATUS: {status_icon}")
    print(f"   JUMLAH ARTIKEL: {len(docs)}")
    print(f"   {index_msg}")
    print("   " + "-"*60)

    # List Judul
    for k, doc in enumerate(docs):
        print(f"   {k+1}. {doc['title']}")

    print("   " + "-"*60)

print("\n" + "="*85)
print(f" Total Klaster Valid tersimpan di 'clusters_list': {len(clusters_list)}")
print("="*85 + "\n")

PENGELOMPOKAN DOKUMEN (CLUSTERING)
================================================================================

 CLUSTER ID: 0
   STATUS:  VALID (Proses ke Summarization)
   JUMLAH ARTIKEL: 2
   TARGET_INDEX = 0
   ------------------------------------------------------------
   1. Harga PS5 Terbaru Januari 2026 di Indonesia, Varian Slim 1TB Turun Harga
   2. GTA 6 Meluncur November 2026, Xbox Terancam Kalah Pamor dari PS5
   ------------------------------------------------------------

 CLUSTER ID: 1
   STATUS:  VALID (Proses ke Summarization)
   JUMLAH ARTIKEL: 2
   TARGET_INDEX = 1
   ------------------------------------------------------------
   1. TV Portabel LG StanbyME 2 Bisa Dilepas Pasang, Ini Spesifikasi dan Harganya di Indonesia
   2. LG Indonesia akan Naikkan Harga TV hingga 7 Persen Imbas Krisis Chip Global
   ------------------------------------------------------------

 CLUSTER ID: 2
   STATUS:  VALID (Proses ke Summarization)
   JUMLAH ARTIKEL: 3
   TARGET_INDEX = 2
   ------------------------------------------------------------
   1. Menakar Masa Depan AI: Mengutamakan Dampak, Bukan Kompleksitas
   2. Lenovo Ungkap Tren AI ASEAN, Hybrid AI Kini Jadi Keharusan
   3. 5 HP Rp 1 Jutaan Sudah Punya Fitur AI, Layak Dilirik di 2026
   ------------------------------------------------------------

 CLUSTER ID: 3
   STATUS:  VALID (Proses ke Summarization)
   JUMLAH ARTIKEL: 2
   TARGET_INDEX = 3
   ------------------------------------------------------------
   1. Startup Casion Lolos Grab Ventures Velocity Batch 8, Tancap Gas Ekspansi Jaringan Charging EV di Indonesia
   2. Grab Ventures Velocity Batch 8 Resmi Lulus, Startup Hijau Jadi Sorotan
   ------------------------------------------------------------

 CLUSTER ID: 4
   STATUS:  VALID (Proses ke Summarization)
   JUMLAH ARTIKEL: 5
   TARGET_INDEX = 4
   ------------------------------------------------------------
   1. Top 3 Tekno: Aplikasi Gojek Error 13 Januari hingga Jadwal Swiss Stage M7
   2. Sempat Error, Gojek Sebut Kendala Teknis Selasa Kemarin Telah Teratasi
   3. Gojek Sempat Error Kini Sudah Kembali Normal
   4. Aplikasi Gojek Error Hari Ini, Pengguna Mengeluh Tak Bisa Tentukan Lokasi Tujuan
   5. Gojek Down di 13 Januari 2026? Banyak User Keluhkan Layanan yang Bermasalah
   ------------------------------------------------------------

 CLUSTER ID: 5
   STATUS:  VALID (Proses ke Summarization)
   JUMLAH ARTIKEL: 3
   TARGET_INDEX = 5
   ------------------------------------------------------------
   1. Top 3 Tekno: Bocoran Xiaomi 17 Max hingga Penampakan Oppo Reno15 Series Jelang Rilis
   2. Intip Oppo Reno15 Series dari Dekat Jelang Rilis 23 Januari, Ini Tampilan Desain Barunya
   3. Xiaomi 17 Max Siap Debut, Ini Perkiraan Jadwal Rilis dan Spesifikasinya
   ------------------------------------------------------------

 CLUSTER ID: 6
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Hands-On Realme C85 5G, HP Kelas Menengah dengan Ketahanan Air Panas Standar Industri
   ------------------------------------------------------------

 CLUSTER ID: 7
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Grok AI Milik Elon Musk Bikin Geger, Regulator Inggris Selidiki X
   ------------------------------------------------------------

 CLUSTER ID: 8
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. iQOO Z11 Turbo Bisa Pangkas Gangguang Wi-Fi hingga 76 Persen Berkat Chip Gaming Thunder Z1
   ------------------------------------------------------------

 CLUSTER ID: 9
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Perbedaan Restart dan Shutdown HP, Mana yang Lebih Baik untuk Dongkrak Performa?
   ------------------------------------------------------------

 CLUSTER ID: 10
   STATUS:  VALID (Proses ke Summarization)
   JUMLAH ARTIKEL: 2
   TARGET_INDEX = 6
   ------------------------------------------------------------
   1. Xiaomi Punya HP Lebih Tipis dari iPhone Air, Tapi Urung Diproduksi Massal
   2. Spesifikasi Honor Magic 8 Pro Air Bocor Jelang Rilis, Andalkan Kamera Kelas Atas dan Bodi Tipis
   ------------------------------------------------------------

 CLUSTER ID: 11
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Apple Rajai Pasar Smartphone Global 2025, Geser Samsung dari Posisi Teratas
   ------------------------------------------------------------

 CLUSTER ID: 12
   STATUS:  VALID (Proses ke Summarization)
   JUMLAH ARTIKEL: 2
   TARGET_INDEX = 7
   ------------------------------------------------------------
   1. Modena Perluas Layanan Langganan, Bidik Pasar B2B hingga Dapur Berbasis AI
   2. Modena Luncurkan Next Home dan Layanan Subscription Pertama di Indonesia
   ------------------------------------------------------------

 CLUSTER ID: 13
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Waspada Login Palsu, Peretas Manfaatkan Trik Browser-in-the-Browser untuk Bobol Akun Facebook dkk
   ------------------------------------------------------------

 CLUSTER ID: 14
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Fitur Verifikasi Usia Roblox Masih Bermasalah, Anak Bisa Terbaca Dewasa
   ------------------------------------------------------------

 CLUSTER ID: 15
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Apple Siapkan 4 MacBook Baru pada 2026, Ada Versi Murah hingga Pro OLED Layar Sentuh
   ------------------------------------------------------------

 CLUSTER ID: 16
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Lenovo Tech Day 2026 Ungkap Pergeseran Besar Strategi AI Perusahaan
   ------------------------------------------------------------

 CLUSTER ID: 17
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Layar Galaxy Z Fold 8 Bakal Mulus tanpa Garis Lipatan, Ini Rahasianya
   ------------------------------------------------------------

 CLUSTER ID: 18
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Review Vivo X300 Pro: dari Uji Ketahanan Baterai hingga Performa Gaming
   ------------------------------------------------------------

 CLUSTER ID: 19
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Wamen Bima Arya: Kebijakan Daerah Jangan Matikan Layanan Digital
   ------------------------------------------------------------

 CLUSTER ID: 20
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. TheoTown, Game Bangun Kota Lintas Platform dengan Transportasi dan Bencana Dinamis
   ------------------------------------------------------------

 CLUSTER ID: 21
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Apple Creator Studio Siap Hadir di Indonesia, Final Cut Pro dkk Bisa Diakses Mulai Rp 99 Ribu
   ------------------------------------------------------------

 CLUSTER ID: 22
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Civilization VII Arcade Edition Masuk Apple Arcade 5 Februari, Bisa Main di iPhone, iPad, dan Mac
   ------------------------------------------------------------

 CLUSTER ID: 23
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. 5 Merk Soundbar Berkualitas dengan Harga yang Murah di 2026
   ------------------------------------------------------------

 CLUSTER ID: 24
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Claude for Healthcare Meluncur, Jawaban Anthropic atas ChatGPT Health
   ------------------------------------------------------------

 CLUSTER ID: 25
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Unboxing Redmi Note 15 Pro+, Dua Fitur Ini Bikin Kesan Pertamanya Berbeda
   ------------------------------------------------------------

 CLUSTER ID: 26
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Top 3 Tekno: Kode Redeem TheoTown Terbaru Januari 2026 Paling Diburu
   ------------------------------------------------------------

 CLUSTER ID: 27
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Jadwal Swiss Stage M7 MLBB Hari Ini 17 Januari: Onic Bertaruh Nasib Lawan Team Falcons
   ------------------------------------------------------------

 CLUSTER ID: 28
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Cara Membuat Fitur Produk Anda Menonjol dengan Alat Peningkatan Video
   ------------------------------------------------------------

 CLUSTER ID: 29
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Fitbit dan Strava Jadi Aplikasi Paling Banyak Kumpulkan Data Pengguna
   ------------------------------------------------------------

 CLUSTER ID: 30
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Resident Evil Showcase Digelar 16 Januari 2026, Gameplay Requiem Siap Dipamerkan
   ------------------------------------------------------------

 CLUSTER ID: 31
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Ini Penjelasan Meta ke Komdigi Soal Isu Kebocoran Data dan Reset Password Instagram
   ------------------------------------------------------------

 CLUSTER ID: 32
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Apple Pastikan Gemini Tidak Terasa seperti 'Google' di Siri
   ------------------------------------------------------------

 CLUSTER ID: 33
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. Gemini Produksi 1 Miliar Gambar hanya dalam 2 Bulan Berkat Nano Banana Pro
   ------------------------------------------------------------

 CLUSTER ID: 34
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. OpenAI Mulai Uji Iklan di ChatGPT, Ini Dampaknya bagi Pengguna Gratis
   ------------------------------------------------------------

 CLUSTER ID: 35
   STATUS:  SKIP (Artikel Tunggal/Kurang)
   JUMLAH ARTIKEL: 1
   (Tidak masuk list analisis)
   ------------------------------------------------------------
   1. NumoFest 2026 Dorong Digitalisasi UMKM Lewat Inovasi QRIS Tap di 9 Kota
   ------------------------------------------------------------

=====================================================================================
 Total Klaster Valid tersimpan di 'clusters_list': 8
=====================================================================================

In [ ]:
# @title Konfigurasi & Load Target Klaster
import pandas as pd
import numpy as np
import re

pd.set_option('display.max_colwidth', None)

# --- KONFIGURASI ---
USE_STEMMING = False
TARGET_CLUSTER_INDEX = 2


if not clusters_list:
    raise ValueError(" Error: Tidak ada klaster yang tersedia di 'clusters_list'!")

target_cluster = clusters_list[TARGET_CLUSTER_INDEX]

print(f"Klaster Topik Index [{TARGET_CLUSTER_INDEX}]")
print(f"Judul Utama: '{target_cluster[0]['title'][:500]}.'")
print(f"Jumlah Artikel dalam Klaster: {len(target_cluster)}")
print(f"Mode Stemming aktif: {USE_STEMMING}")

Klaster Topik Index [2]
Judul Utama: 'Menakar Masa Depan AI: Mengutamakan Dampak, Bukan Kompleksitas.'
Jumlah Artikel dalam Klaster: 3
Mode Stemming aktif: False

In [ ]:
#text cleaning & Sentence Splitting
print("[Processing] Memulai Preprocessing...\n")

preprocessor = TextPreprocessor()
all_data = []

for doc_idx, art in enumerate(target_cluster):
    original_text = art['content']

    clean_display = preprocessor.clean_text_display(original_text)

    sents = preprocessor.split_sentences(clean_display)

    print("="*60)
    print(f"🔍 DEMO TAHAPAN PREPROCESSING (DOKUMEN {doc_idx + 1})")
    print("="*60)
    print(f"🟢 1. TEKS MENTAH AWAL:\n{original_text[:1000000]}...\n")
    print(f"🟢 2. HASIL TAHAP 1 - DISPLAY CLEANSING:\n{clean_display[:1000000]}...\n")


    print(f"🟢 3. HASIL TAHAP 2 - SENTENCE SPLITTING (3 Kalimat Pertama):")
    for i, s in enumerate(sents[:3]):
        print(f"   [{i+1}] {s}")

    print(f"\n🟢 4. HASIL TAHAP 3 - LENGTH FILTERING & CASE FOLDING:")

    for sent_idx, s in enumerate(sents):
        s = s.strip()

        if len(s) >= 20 and re.search(r'[a-zA-Z]', s):

            calc_text = preprocessor.case_folding_and_remove_artifacts(s)

            if sent_idx < 3:
                print(f"   [Valid] -> {calc_text}")

            # Simpan ke memori
            meta = {
                'doc_id': doc_idx + 1,
                'sent_id': sent_idx + 1,
                'original_text': s,      # Teks ini untuk ditampilkan di ringkasan akhir
                'calc_text': calc_text   # Teks ini yang akan dikonversi SBERT
            }
            all_data.append(meta)

        else:
            if sent_idx < 3:
                print(f"   [Dibuang (Noise/Terlalu Pendek)] -> {s}")

    print("="*60, "\n")

print(f"✅ Preprocessing Selesai untuk seluruh dokumen.")
print(f"✅ Total Kalimat Valid: {len(all_data)} kalimat\n")

# Menampilkan hasil akhir DataFrame
print("📊 Sample Data Tersimpan (Format Input SBERT):")
df_prep = pd.DataFrame(all_data)[['doc_id', 'sent_id', 'original_text', 'calc_text']]
df_prep.columns = ['Doc ID', 'Sent ID', 'Kalimat Asli (Tampilan)', 'Kalimat Bersih (Input SBERT)']

# Menampilkan 10 baris pertama di tabel. Ubah head(10) menjadi display(df_prep) jika ingin melihat semua baris.
display(df_prep.head(10))

[Processing] Memulai Preprocessing...

============================================================
🔍 DEMO TAHAPAN PREPROCESSING (DOKUMEN 1)
============================================================
🟢 1. TEKS MENTAH AWAL:
Liputan6.com, Jakarta -Di tengah perlombaan global mengadopsi kecerdasan buatan (AI), talenta Indonesia mulai mengambil peran krusial di pusat inovasi dunia. Product Manager di Google Amerika Serikat, Juan Anugraha Djuwadi, kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi AI dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global. Dalam webinar bertajuk “AI Streamline Your Business: Build Internal Apps with AI” baru-baru ini, Juan membedah peta jalan pengembangan AI yang melampaui sekadar kecanggihan teknis. Baginya, kunci utama efektivitas AI terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat. Juan, yang merupakan alumnus Columbia University, menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi. “Pengguna tidak peduli seberapa canggih teknologi di belakang layar. Mereka peduli apakah solusi itu berguna dan menyelesaikan masalah nyata,” ujar Juan, dikutip Kamis (15/1/2026). Prinsip ini diterjemahkan ke dalam dua filosofi kunci:“less is more”dan“the details matter.”Menurutnya, dalam skala pengguna miliaran seperti di Google, detail sekecil apa pun menjadi isu strategis. Kegagalan sistem sebesar satu persen saja dapat berdampak pada jutaan orang. Persfektif ini dinilai sangat relevan bagi pemerintah Indonesia dan perusahaan BUMN yang tengah mengintegrasikan AI dalam layanan publik berskala nasional. Terkait proses pengambilan keputusan, Juan menawarkan pendekatan moderat antara data dan intuisi. Ia mengibaratkan data sebagai kompas untuk optimasi efisiensi dan akurasi, namun terobosan besar tetap membutuhkan visi manusia. “Data memvalidasi masa kini, namun intuisi mendefinisikan masa depan,” ungkapnya. Pendekatan ini menjadi krusial bagi para regulator dan pemimpin perusahaan di Asia Pasifik (APAC) agar tidak hanya bersikap reaktif terhadap tren, tetapi mampu menjadi visioner dalam merancang ekosistem digital. Tantangan di Pasar Indonesia Menyoroti lanskap digital di Tanah Air, Juan melihat adanya perbedaan fase kematangan antara pasar Amerika Serikat (AS) dan Indonesia. Jika AS sudah mapan dalam hal monetisasi perangkat lunak, Indonesia masih berada dalam tahap transisi yang dinamis. Ia memprediksi, seiring berkembangnya ekosistem digital di Indonesia, isu mengenai privasi data, etika AI, dan akuntabilitas akan menjadi agenda utama yang tak terelakkan. Inovasi AI yang sukses di wilayah dengan keberagaman sosial tinggi seperti Indonesia dan APAC haruslah bersifat kontekstual dan berbasis pada kepercayaan. Mantan profesional di Niantic dan Activision ini juga memproyeksikan pergeseran fundamental dalam lima tahun mendatang melalui demokratisasi AI. Ia memperkirakan lahirnya era“software on-the-fly”,di mana perangkat lunak dihasilkan secarareal-timesesuai kebutuhan instan pengguna, baik melalui antarmuka teks maupun suara. Dengan rekam jejak panjang di industri teknologi dan hiburan global, Juan Djuwadi membuktikan bahwa peran talenta Indonesia bukan sekadar pelengkap. Mereka adalah kontributor strategis yang turut menentukan arah teknologi masa depan yang lebih beretika dan berorientasi pada kepentingan manusia....

🟢 2. HASIL TAHAP 1 - DISPLAY CLEANSING:
Di tengah perlombaan global mengadopsi kecerdasan buatan (AI), talenta Indonesia mulai mengambil peran krusial di pusat inovasi dunia. Product Manager di Google Amerika Serikat, Juan Anugraha Djuwadi, kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi AI dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global. Dalam webinar bertajuk AI Streamline Your Business: Build Internal Apps with AI baru-baru ini, Juan membedah peta jalan pengembangan AI yang melampaui sekadar kecanggihan teknis. Baginya, kunci utama efektivitas AI terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat. Juan, yang merupakan alumnus Columbia University, menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi. Pengguna tidak peduli seberapa canggih teknologi di belakang layar. Mereka peduli apakah solusi itu berguna dan menyelesaikan masalah nyata, ujar Juan, dikutip Kamis (15/1/2026). Prinsip ini diterjemahkan ke dalam dua filosofi kunci:less is moredanthe details matter.Menurutnya, dalam skala pengguna miliaran seperti di Google, detail sekecil apa pun menjadi isu strategis. Kegagalan sistem sebesar satu persen saja dapat berdampak pada jutaan orang. Persfektif ini dinilai sangat relevan bagi pemerintah Indonesia dan perusahaan BUMN yang tengah mengintegrasikan AI dalam layanan publik berskala nasional. Terkait proses pengambilan keputusan, Juan menawarkan pendekatan moderat antara data dan intuisi. Ia mengibaratkan data sebagai kompas untuk optimasi efisiensi dan akurasi, namun terobosan besar tetap membutuhkan visi manusia. Data memvalidasi masa kini, namun intuisi mendefinisikan masa depan, ungkapnya. Pendekatan ini menjadi krusial bagi para regulator dan pemimpin perusahaan di Asia Pasifik (APAC) agar tidak hanya bersikap reaktif terhadap tren, tetapi mampu menjadi visioner dalam merancang ekosistem digital. Tantangan di Pasar Indonesia Menyoroti lanskap digital di Tanah Air, Juan melihat adanya perbedaan fase kematangan antara pasar Amerika Serikat (AS) dan Indonesia. Jika AS sudah mapan dalam hal monetisasi perangkat lunak, Indonesia masih berada dalam tahap transisi yang dinamis. Ia memprediksi, seiring berkembangnya ekosistem digital di Indonesia, isu mengenai privasi data, etika AI, dan akuntabilitas akan menjadi agenda utama yang tak terelakkan. Inovasi AI yang sukses di wilayah dengan keberagaman sosial tinggi seperti Indonesia dan APAC haruslah bersifat kontekstual dan berbasis pada kepercayaan. Mantan profesional di Niantic dan Activision ini juga memproyeksikan pergeseran fundamental dalam lima tahun mendatang melalui demokratisasi AI. Ia memperkirakan lahirnya erasoftware on-the-fly, di mana perangkat lunak dihasilkan secarareal-timesesuai kebutuhan instan pengguna, baik melalui antarmuka teks maupun suara. Dengan rekam jejak panjang di industri teknologi dan hiburan global, Juan Djuwadi membuktikan bahwa peran talenta Indonesia bukan sekadar pelengkap. Mereka adalah kontributor strategis yang turut menentukan arah teknologi masa depan yang lebih beretika dan berorientasi pada kepentingan manusia....

🟢 3. HASIL TAHAP 2 - SENTENCE SPLITTING (3 Kalimat Pertama):
   [1] Di tengah perlombaan global mengadopsi kecerdasan buatan (AI), talenta Indonesia mulai mengambil peran krusial di pusat inovasi dunia.
   [2] Product Manager di Google Amerika Serikat, Juan Anugraha Djuwadi, kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi AI dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global.
   [3] Dalam webinar bertajuk AI Streamline Your Business: Build Internal Apps with AI baru-baru ini, Juan membedah peta jalan pengembangan AI yang melampaui sekadar kecanggihan teknis.

🟢 4. HASIL TAHAP 3 - LENGTH FILTERING & CASE FOLDING:
   [Valid] -> di tengah perlombaan global mengadopsi kecerdasan buatan ai talenta indonesia mulai mengambil peran krusial di pusat inovasi dunia
   [Valid] -> product manager di google amerika serikat juan anugraha djuwadi kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi ai dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global
   [Valid] -> dalam webinar bertajuk ai streamline your business build internal apps with ai barubaru ini juan membedah peta jalan pengembangan ai yang melampaui sekadar kecanggihan teknis
============================================================

============================================================
🔍 DEMO TAHAPAN PREPROCESSING (DOKUMEN 2)
============================================================
🟢 1. TEKS MENTAH AWAL:
Liputan6.com, Jakarta -Adopsi kecerdasan buatan (AI) di kawasan ASEAN terus menunjukkan tren positif. Data terbaru yang terungkap dalam konferensi persLenovo Tech Day 2026menunjukkan 67 persen organisasi di kawasan ASEAN+ sudah melakukan uji coba AI secara sistematis. Angka ini menegaskan satu hal. AI tidak lagi sekadar eksperimen. Perusahaan mulai mencari cara agar teknologi ini benar-benar berdampak bagi bisnis. Bukan lagi soal membangun model AI, tetapi bagaimana mengintegrasikannya dengan perangkat, infrastruktur, dan sistem sudah berjalan. Sejumlah sektor tercatat menjadi pionir dalam penerapan AI, di antaranya telekomunikasi, layanan kesehatan, dan pemerintah. Meski begitu, perusahaan-perusahaan masih menghadapi tantangan besar, terutama dalam mengintegrasikan AI ke dalam lingkungan hybrid yang kompleks. Dalam kesempatan sama, General Manager, Budi Janto menilai pendekatan AI yang mengandalkan sumber daya manusia sudah tidak relevan di kawasan ASEAN. “Di lingkungan ASEAN sendiri,strategic AI yang berbasispublic moneyitu sudah nggak praktis. Karena kenapa? Beban untuk load-nya itu sudah tidak mumpuni. Jadi hybrid AI itu bukan pilihan, tapi itu sudah keharusan bagi perusahaan-perusahaan yang di ASEAN,” ujar Budi Janto, di Jakarta, baru-baru ini. Seiring dengan hal itu, fokus perusahaan di ASEAN+ mulai beralih ke Agentic AI. Tercatat peningkatan fokus pada Agentic AI mencapai 91 persen secara tahunan (year on year). Sebanyak 43 persen disebut masih membutuhkan waktu hingga 12 bulan untuk mencapai kesiapan. Sementara hanya 11 persen organisasi yang menyatakan siap untuk melakukan scalling Agentic AI. “Hanya ada 11 persen ini cukup gede dari jumlahcompanydi ASEAN. 11 persen ini yang bilang bahwa dia siap untuk melakukan skalanyaagency AI,” ungkap Budi. Kesenjangan kesiapan ini rupanya masih menunjukkan adanya tantangan mendasar dalam penerapan AI. Terdapat tiga tantangan utama menurut para CIO di ASEAN+, yakni penerapan AI yang dinilai masih belum optimal, keamanan data, serta kualitas data yang belum memadai. Di sisi lain, kawasan ASEAN memiliki potensi besar sebagai lingkungan uji coba ideal untuk Agentic AI. Berkat kelincahan dan kematangan tata kelola di kawasan ASEAN menjadikannya sebagai lingkungan uji coba yang ideal untuk Agentic AI.yang terus berkembang. “Pemenangnya di eraagentic AIbukan yang paling cepat bergerak, tapi mereka bilang yang paling dapat dipercaya, dan paling dapat tata kelolanya baik,” tegas Budi. Di sisi lain,LenovoresmiLenovo Tech Day 2026dengan tema “The Race for EnterpriseAI”. Forum ini menjadi panggung perusahaan asal China tersebut untuk memaparkan arah perkembangan adopsikecerdasan buatan(AI) di sektor perusahaan. Dalam acara yang digelar di Jakarta, Selasa (13/1/2026), Lenovo juga memperkenalkan CIO Playbook 2026. Laporan tahunan ini merupakan hasil kolaborasi Lenovo dan IDC yang memasuki tahun keempat. CIO Playbook 2026 disusun dari riset terhadap lebih dari 920 CIO dan direktur TI di 10 pasar Asia Pasifik, termasuk kawasan ASEAN. Melalui riset ini, Lenovo memetakan kesiapan, kapabilitas, dan prioritas perubahan dalam mengadipsi AI di lingkungan bisnis. Vice President Commercial Portfolio & Product Management Lenovo, Thomas Butler, menegaskan adanya pergeseran besar dalam cara perusahaan memandang AI. “Tahun lalu kita banyak membahas ekonomi AI. Diskusinya masih berada di tahap uji coba dan pilot. Namun kini, prioritas bisnis telah bergeser ke bagaimana AI mampu mendorong peningkatan pendapatan dan profitabilitas,” ujar Thomas. Data CIO Playbook 2026 menunjukkan faktor peningkatan pendapatan melonjak tujuh peringkat dan kini menempati posisi teratas dalam prioritas bisnis. Ini menandai berakhirnya fase eksperimen AI. Perusahaan mulai menuntut dampak bisnis terukur. Prioritas kedua adalah reinvensi bisnis berbasis AI. Transformasi ini menuntut perubahan budaya organisasi serta peningkatan pelatihan karyawan. Model AI kini dibawa langsung ke lingkungan kerja, sehingga karyawan dituntut mampu memahami dan mengintegrasikan proses berbasis AI ke dalam aktivitas sehari-hari. Sementara itu, prioritas ketiga adalah peningkatan pengalaman dan kepuasan. Pada 2026 fokus AI didominasi oleh pendekatan berbasis hasil (outcome-based), yang mengisi tiga posisi teratas dalam strategi perusahaan. Lenovo juga mengungkap bahwa 96% perusahaan berencana meningkatkan investasi AI pada 2026. Investasi tersebut mencakup pengembangan AI generatif, agen AI, komputasi cloud publik, layanan AI, infrastruktur AI on-premise, serta aspek keamanan, kepercayaan, dan transparansi AI. “Kini, perusahaan tidak hanya melihat pengembalian investasi secara langsung dari AI, tetapi juga peningkatan layanan pelanggan, keterlibatan karyawan yang lebih tinggi, serta pengambilan keputusan yang semakin baik,” terang Thomas. Data Lenovo menunjukkan lonjakan signifikan dalam tahap adopsi AI. Dari 2025 ke 2026, tahap implementasi dan uji coba AI meningkat menjadi 66 persen. Adopsi AI tidak lagi terbatas pada fungsi IT seperti analitik data, keamanan siber dan pengembangan perangkat lunak, tetapi juga mengarah ke fungsi non-IT. “Di internal Lenovo sendiri, kami telah memanfaatkan AI dalam rantai pasok dan perencanaan logistik,” ujar Thomas. Dalam skala yang lebih luas, Lenovo mengidentifikasi sejumlah faktor kunci keberhasilan penerapan AI. Beberapa diantaranya yaitu: “Jika melihat keseluruhan faktor tersebut, inilah alasan mengapa terjadi pergeseran menuju penerapan AI berbasis hibrida. Saat ini, hampir 90 persen organisasi menyatakan lebih memilih atau tengah beralih ke model penerapan AI hibrida,” ungkap Thomas. Penerapan AI Hybrid turut dipengaruhi oleh tingginya biaya pengelolaan data di cloud, serta kekhawatiran terkait keamanan dan privasi data. Kondisi ini secara langsung membatasi perusahaan untuk mengimplementasikan AI di lingkungan cloud. Maka, data diproses di perangkat lokal dan edge akan dikombinasikan dengan kemampuan cloud. Sehingga pendekatan hybrid menjadi standar baru dalam penerapan AI di lingkungan perusahaan. Sejalan dengan hal ini, prioritas investasi TI pun bergeser ke arah penerapan perangkay AI guna meningkatkan produktivitas dan mendukung proses inferensi AI secara lokal. Perangkat-perangkat yang kini dibawa Lenovo ke pasar telah memiliki kapabilitas AI. Artinya, perangkat tersebut memiliki kemampuan dan kinerja yang diperlukan untuk menjalankan model AI secara lokal di sisi edge ....

🟢 2. HASIL TAHAP 1 - DISPLAY CLEANSING:

,Doc ID,Sent ID,Kalimat Asli (Tampilan),Kalimat Bersih (Input SBERT)
0,1,1,"Di tengah perlombaan global mengadopsi kecerdasan buatan (AI), talenta Indonesia mulai mengambil peran krusial di pusat inovasi dunia.",di tengah perlombaan global mengadopsi kecerdasan buatan ai talenta indonesia mulai mengambil peran krusial di pusat inovasi dunia
1,1,2,"Product Manager di Google Amerika Serikat, Juan Anugraha Djuwadi, kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi AI dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global.",product manager di google amerika serikat juan anugraha djuwadi kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi ai dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global
2,1,3,"Dalam webinar bertajuk AI Streamline Your Business: Build Internal Apps with AI baru-baru ini, Juan membedah peta jalan pengembangan AI yang melampaui sekadar kecanggihan teknis.",dalam webinar bertajuk ai streamline your business build internal apps with ai barubaru ini juan membedah peta jalan pengembangan ai yang melampaui sekadar kecanggihan teknis
3,1,4,"Baginya, kunci utama efektivitas AI terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat.",baginya kunci utama efektivitas ai terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat
4,1,5,"Juan, yang merupakan alumnus Columbia University, menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi.",juan yang merupakan alumnus columbia university menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi
5,1,6,Pengguna tidak peduli seberapa canggih teknologi di belakang layar.,pengguna tidak peduli seberapa canggih teknologi di belakang layar
6,1,7,"Mereka peduli apakah solusi itu berguna dan menyelesaikan masalah nyata, ujar Juan, dikutip Kamis (15/1/2026).",mereka peduli apakah solusi itu berguna dan menyelesaikan masalah nyata ujar juan dikutip kamis
7,1,8,"Prinsip ini diterjemahkan ke dalam dua filosofi kunci:less is moredanthe details matter.Menurutnya, dalam skala pengguna miliaran seperti di Google, detail sekecil apa pun menjadi isu strategis.",prinsip ini diterjemahkan ke dalam dua filosofi kunciless is moredanthe details mattermenurutnya dalam skala pengguna miliaran seperti di google detail sekecil apa pun menjadi isu strategis
8,1,9,Kegagalan sistem sebesar satu persen saja dapat berdampak pada jutaan orang.,kegagalan sistem sebesar satu persen saja dapat berdampak pada jutaan orang
9,1,10,Persfektif ini dinilai sangat relevan bagi pemerintah Indonesia dan perusahaan BUMN yang tengah mengintegrasikan AI dalam layanan publik berskala nasional.,persfektif ini dinilai sangat relevan bagi pemerintah indonesia dan perusahaan bumn yang tengah mengintegrasikan ai dalam layanan publik berskala nasional

In [ ]:
#text celaning & Sentence Splitting
print("[Processing]...")

all_data = []
calc_texts = []   # (clean/stemmed teks)

for doc_idx, art in enumerate(target_cluster):

    clean = preprocessor.clean_text_display(art['content'])

    sents = preprocessor.split_sentences(clean)

    for sent_idx, s in enumerate(sents):
        s = s.strip()
        if len(s) >= 20 and re.search(r'[a-zA-Z]', s):
            clean_artifact_text = preprocessor.case_folding_and_remove_artifacts(s)
            if USE_STEMMING:
                processed = preprocessor.stemming_process(clean_artifact_text)
            else:
                processed = clean_artifact_text

            meta = {
                'text': s,
                'doc_id': doc_idx + 1,
                'sent_id': sent_idx + 1,
                'calc_text': processed
            }
            all_data.append(meta)
            calc_texts.append(processed)

print(f" Preprocessing Selesai.")
print(f" Total Kalimat Valid: {len(all_data)} kalimat")

print("\n Sample Data (Original vs Calculation Input):")
df_prep = pd.DataFrame(all_data)[['text', 'calc_text']]
df_prep.columns = ['Original Text (Display)', 'Cleaned text for Embedding Input (SBERT)']
display(df_prep)

[Processing]...
 Preprocessing Selesai.
 Total Kalimat Valid: 115 kalimat

 Sample Data (Original vs Calculation Input):

,Original Text (Display),Cleaned text for Embedding Input (SBERT)
0,"Di tengah perlombaan global mengadopsi kecerdasan buatan (AI), talenta Indonesia mulai mengambil peran krusial di pusat inovasi dunia.",di tengah perlombaan global mengadopsi kecerdasan buatan ai talenta indonesia mulai mengambil peran krusial di pusat inovasi dunia
1,"Product Manager di Google Amerika Serikat, Juan Anugraha Djuwadi, kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi AI dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global.",product manager di google amerika serikat juan anugraha djuwadi kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi ai dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global
2,"Dalam webinar bertajuk AI Streamline Your Business: Build Internal Apps with AI baru-baru ini, Juan membedah peta jalan pengembangan AI yang melampaui sekadar kecanggihan teknis.",dalam webinar bertajuk ai streamline your business build internal apps with ai barubaru ini juan membedah peta jalan pengembangan ai yang melampaui sekadar kecanggihan teknis
3,"Baginya, kunci utama efektivitas AI terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat.",baginya kunci utama efektivitas ai terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat
4,"Juan, yang merupakan alumnus Columbia University, menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi.",juan yang merupakan alumnus columbia university menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi
...,...,...
110,"Potret HP Infinix Smart 10 Plus, HP Rp 1 jutaan terbaru yang hadir dengan dukungan AI hingga sertifikat anti debu dan air, IP 64 (Foto: Infinix).",potret hp infinix smart plus hp rp jutaan terbaru yang hadir dengan dukungan ai hingga sertifikat anti debu dan air ip foto infinix
111,"Infinix Smart 10 Plus hadir dengan pengalaman kecerdasan buatan (AI) yang menonjol, salah satu daya tariknya terletak pada kehadiran Folax, asisten virtual berbasis AI.",infinix smart plus hadir dengan pengalaman kecerdasan buatan ai yang menonjol salah satu daya tariknya terletak pada kehadiran folax asisten virtual berbasis ai
112,"Folax dirancang untuk mempermudah aktivitas harian pengguna, mampu menyusun pesan, menjadwalkan aktivitas, hingga mencari informasi dengan cepat.",folax dirancang untuk mempermudah aktivitas harian pengguna mampu menyusun pesan menjadwalkan aktivitas hingga mencari informasi dengan cepat
113,Ponsel ini dibekali baterai berkapasitas 6.000 m Ah dengan dukungan fast charging 18 W.,ponsel ini dibekali baterai berkapasitas m ah dengan dukungan fast charging w
114,"Infinix Smart 10 Plus mengusung layar 6,67 inci dengan refresh rate hingga 120 Hz dan tingkat kecerahan 700 nits, memberikan tampilan visual yang mulus dan cerah.",infinix smart plus mengusung layar inci dengan refresh rate hingga hz dan tingkat kecerahan nits memberikan tampilan visual yang mulus dan cerah

In [ ]:
#Embedding Generation (Sentence-BERT)
import pandas as pd
import numpy as np

sent_vecs = embedder.get_embeddings(calc_texts)

query_vec = np.mean(sent_vecs, axis=0)


print(" INFORMASI STRUKTUR DATA:")
print(f"   • Tipe Data Output : {type(sent_vecs)}")
print(f"   • Matriks Kalimat  : {sent_vecs.shape}  -> (Total Kalimat, Dimensi Model)")
print(f"   • Vektor Query     : {query_vec.shape}     -> (Dimensi Model,)")

 INFORMASI STRUKTUR DATA:
   • Tipe Data Output : <class 'numpy.ndarray'>
   • Matriks Kalimat  : (115, 384)  -> (Total Kalimat, Dimensi Model)
   • Vektor Query     : (384,)     -> (Dimensi Model,)

In [ ]:
# (dimensi Sample 5 Kalimat Pertama)

num_preview_dims = 384
cols = [f"Dim_{i+1}" for i in range(num_preview_dims)]

if sent_vecs.ndim == 1:
    df_vec_preview = pd.DataFrame(sent_vecs[:num_preview_dims].reshape(1, -1), columns=cols)
    df_vec_preview.insert(0, "Text Snippet", [calc_text[:10000] ])
elif sent_vecs.ndim == 2:
    df_vec_preview = pd.DataFrame(sent_vecs[:100, :num_preview_dims], columns=cols)
    df_vec_preview.insert(0, "Text Snippet", [t[:1000] for t in calc_texts[:100]])
else:
    raise ValueError("sent_vecs has unexpected dimensions.")

display(df_vec_preview)

,Text Snippet,Dim_1,Dim_2,Dim_3,Dim_4,Dim_5,Dim_6,Dim_7,Dim_8,Dim_9,...,Dim_375,Dim_376,Dim_377,Dim_378,Dim_379,Dim_380,Dim_381,Dim_382,Dim_383,Dim_384
0,di tengah perlombaan global mengadopsi kecerdasan buatan ai talenta indonesia mulai mengambil peran krusial di pusat inovasi dunia,0.189700,0.081387,-0.249778,-0.070411,-0.109405,-0.168465,0.067418,0.196160,-0.086247,...,0.108329,-0.017193,0.018506,0.205614,-0.242774,0.133608,0.242542,0.170082,-0.124843,-0.024607
1,product manager di google amerika serikat juan anugraha djuwadi kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi ai dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global,-0.217632,0.020319,-0.059410,-0.260153,-0.133210,-0.095813,0.198513,0.035066,-0.018904,...,0.189109,0.043128,-0.002502,-0.194602,-0.037253,0.265025,-0.016554,-0.284555,0.035442,0.128904
2,dalam webinar bertajuk ai streamline your business build internal apps with ai barubaru ini juan membedah peta jalan pengembangan ai yang melampaui sekadar kecanggihan teknis,-0.145410,-0.227322,-0.021296,-0.179999,0.148238,0.042999,-0.256261,-0.129809,-0.015015,...,0.122709,0.105238,-0.003897,-0.171966,0.039623,0.250100,-0.243303,0.139276,0.290651,0.088567
3,baginya kunci utama efektivitas ai terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat,-0.195242,-0.087658,-0.182792,0.014352,-0.080117,-0.143006,0.019054,0.245063,0.019270,...,0.100557,0.011179,0.196877,0.245222,-0.054827,0.111626,0.087833,0.112648,0.261143,0.152891
4,juan yang merupakan alumnus columbia university menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi,-0.112157,-0.066843,-0.038625,-0.252461,-0.017068,-0.261504,-0.028892,0.275552,0.207704,...,0.301913,-0.067475,0.110268,-0.294967,-0.118493,0.054086,-0.115279,0.024385,0.311798,0.105448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,infinix hot i infinix hot i hadir dengan serangkaian fitur kecerdasan buatan ai yang diklaim paling lengkap di kelasnya menjadikannya pilihan menarik di segmen harga terjangkau,-0.090537,0.027703,-0.069617,0.096545,-0.079783,0.006308,0.055922,0.030585,-0.107073,...,0.175018,-0.160670,0.126892,-0.002374,-0.088230,0.076905,0.411613,0.226063,-0.191593,0.193871
96,perangkat ini berjalan di atas sistem operasi infinix xos berbasis android yang dilengkapi dengan empat fitur ai yang disebut onetap infinix ai,-0.122954,-0.087596,-0.018776,-0.281992,-0.125379,0.082617,0.083261,-0.239590,0.133264,...,0.101358,0.135668,0.100846,-0.288046,0.108282,0.288790,-0.070975,0.185214,0.251210,0.205990
97,fiturfitur ini mencakup produktivitas sekali ketuk untuk membantu pengguna membuat daftar tugas catatan dan menjalankan perintah kerja ringan dengan cepat,-0.278670,-0.035580,-0.136952,-0.029451,-0.307695,-0.062887,0.091451,0.211475,0.000005,...,0.143827,0.143560,0.218103,-0.271882,0.293347,0.143143,0.013824,0.439754,-0.093892,0.041276
98,selain itu infinix hot i juga dibekali onetap summarize sebuah fitur yang sangat berguna untuk merangkum teks panjang menjadi poinpoin penting yang mudah dipahami dan onetap answers yang memberikan feedback atau respons instan terhadap pertanyaan umum atau perintah teks,-0.284479,-0.130289,0.060833,0.119596,0.043076,0.097192,0.039742,0.161428,0.062741,...,-0.079612,0.054321,0.208100,0.041677,0.368569,0.126966,0.052585,0.347566,-0.152549,0.043721
99,ponsel ini memiliki kamera utama mp dengan ai dan kamera depan mp yang dilengkapi dengan lampu flash serta fitur fotografi seperti vlog mode dan super night,-0.033727,0.334426,-0.042395,-0.029196,0.418696,-0.001090,-0.100492,-0.084938,0.131937,...,-0.059706,-0.054090,0.055887,-0.148613,0.232752,0.023879,0.084223,0.040752,-0.134952,0.210309

In [ ]:
# Query Vector
print("\n PREVIEW QUERY VECTOR (CENTROID) (10 Dimensi Awal):")
print("   (Rata-rata dari seluruh vektor di atas, merepresentasikan 'topik inti')")
df_query = pd.DataFrame(query_vec.reshape(1, -1)[:, :500], columns=[f"Dim_{i+1}" for i in range(384)])
display(df_query)

# Nilai
print("\n STATISTIK NILAI VEKTOR:")
print(f"   • Nilai Min dalam Matrix : {np.min(sent_vecs):.4f}")
print(f"   • Nilai Max dalam Matrix : {np.max(sent_vecs):.4f}")
print(f"   • Nilai Mean (Rata-rata) : {np.mean(sent_vecs):.4f}")

 PREVIEW QUERY VECTOR (CENTROID) (10 Dimensi Awal):
   (Rata-rata dari seluruh vektor di atas, merepresentasikan 'topik inti')

,Dim_1,Dim_2,Dim_3,Dim_4,Dim_5,Dim_6,Dim_7,Dim_8,Dim_9,Dim_10,...,Dim_375,Dim_376,Dim_377,Dim_378,Dim_379,Dim_380,Dim_381,Dim_382,Dim_383,Dim_384
0,-0.049534,0.067531,-0.109467,-0.124708,0.015067,-0.029547,-0.077547,0.019175,0.005123,0.052746,...,0.073823,0.004224,0.052632,-0.04323,-0.011829,0.109979,0.061422,0.033432,0.107196,0.108115

 STATISTIK NILAI VEKTOR:
   • Nilai Min dalam Matrix : -0.8169
   • Nilai Max dalam Matrix : 1.0014
   • Nilai Mean (Rata-rata) : 0.0002

In [ ]:
# MMR Selection Process (Ranking)

# COMPRESSION_RATE = 0.20
# COMPRESSION_RATE = 0.30
# COMPRESSION_RATE = 0.40
COMPRESSION_RATE = 0.50
# n_teratas= 8

total_sentences_input = len(all_data)
jumlah_terkompresi = int(total_sentences_input * COMPRESSION_RATE)

# selected_data, logs = mmr.select_with_logs(all_data, sent_vecs, query_vec, n=jumlah_terkompresi)
selected_data, logs, heuristic_logs = mmr.select_with_logs(all_data, sent_vecs, query_vec, n=jumlah_terkompresi)

print(f"✅ Jumlah Kalimat Terpilih: {len(selected_data)} dari total {total_sentences_input} kalimat.\n")

print("\n" + "="*80)
df_heuristics = pd.DataFrame(heuristic_logs)
display(df_heuristics)

print("\n" + "="*80)
print("\n TABEL DETAIL SCORING MMR :")
df_logs = pd.DataFrame(logs)

#Output
# df_logs = df_logs[['Step', 'Source', 'MMR Score', 'Relevance', 'Diversity', 'Text']]
df_logs = pd.DataFrame(logs)
display(df_logs)

✅ Jumlah Kalimat Terpilih: 57 dari total 115 kalimat.


================================================================================

,Doc ID,Sent ID,Raw Sim_1,Multiplier,Modified Sim_1,Rule Applied,Text Snippet
0,1,1,0.556876,1.0,0.556876,Baseline (Normal),"di tengah perlombaan global mengadopsi kecerdasan buatan (ai), talenta indonesia mulai mengambil peran krusial di pusat inovasi dunia."
1,1,2,0.603104,1.0,0.603104,Baseline (Normal),"product manager di google amerika serikat, juan anugraha djuwadi, kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi ai dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global."
2,1,3,0.636507,1.0,0.636507,Baseline (Normal),"dalam webinar bertajuk ai streamline your business: build internal apps with ai baru-baru ini, juan membedah peta jalan pengembangan ai yang melampaui sekadar kecanggihan teknis."
3,1,4,0.617614,1.0,0.617614,Baseline (Normal),"baginya, kunci utama efektivitas ai terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat."
4,1,5,0.516686,1.0,0.516686,Baseline (Normal),"juan, yang merupakan alumnus columbia university, menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi."
...,...,...,...,...,...,...,...
110,3,35,0.490535,1.0,0.490535,Baseline (Normal),"potret hp infinix smart 10 plus, hp rp 1 jutaan terbaru yang hadir dengan dukungan ai hingga sertifikat anti debu dan air, ip 64 (foto: infinix)."
111,3,36,0.613007,1.0,0.613007,Baseline (Normal),"infinix smart 10 plus hadir dengan pengalaman kecerdasan buatan (ai) yang menonjol, salah satu daya tariknya terletak pada kehadiran folax, asisten virtual berbasis ai."
112,3,37,0.410591,1.0,0.410591,Baseline (Normal),"folax dirancang untuk mempermudah aktivitas harian pengguna, mampu menyusun pesan, menjadwalkan aktivitas, hingga mencari informasi dengan cepat."
113,3,38,0.263359,1.0,0.263359,Baseline (Normal),ponsel ini dibekali baterai berkapasitas 6.000 m ah dengan dukungan fast charging 18 w.
114,3,39,0.485436,1.0,0.485436,Baseline (Normal),"infinix smart 10 plus mengusung layar 6,67 inci dengan refresh rate hingga 120 hz dan tingkat kecerahan 700 nits, memberikan tampilan visual yang mulus dan cerah."

================================================================================

 TABEL DETAIL SCORING MMR :

,Step,Source,MMR Score,Modified Sim_1 (Rel),Diversity,Text
0,1,"[doc_2, sent_51]",0.505339,0.721913,0.000000,"Dalam skala yang lebih luas, Lenovo mengidentifikasi sejumlah faktor kunci keberhasilan penerapan AI."
1,2,"[doc_2, sent_5]",0.363250,0.700187,0.422936,Perusahaan mulai mencari cara agar teknologi ini benar-benar berdampak bagi bisnis.
2,3,"[doc_3, sent_1]",0.335905,0.705816,0.527220,Tren kecerdasan buatan (AI) semakin merambah ke segmensmartphone entry-leveldan menengah.
3,4,"[doc_2, sent_59]",0.328440,0.717482,0.579326,Perangkat-perangkat yang kini dibawa Lenovo ke pasar telah memiliki kapabilitas AI.
4,5,"[doc_1, sent_16]",0.309667,0.650407,0.485395,"Jika AS sudah mapan dalam hal monetisasi perangkat lunak, Indonesia masih berada dalam tahap transisi yang dinamis."
5,6,"[doc_2, sent_48]",0.307778,0.693046,0.591178,"Dari 2025 ke 2026, tahap implementasi dan uji coba AI meningkat menjadi 66 persen."
6,7,"[doc_1, sent_14]",0.296221,0.678077,0.594778,"Pendekatan ini menjadi krusial bagi para regulator dan pemimpin perusahaan di Asia Pasifik (APAC) agar tidak hanya bersikap reaktif terhadap tren, tetapi mampu menjadi visioner dalam merancang ekosistem digital."
7,8,"[doc_2, sent_6]",0.292543,0.629039,0.492613,"Bukan lagi soal membangun model AI, tetapi bagaimana mengintegrasikannya dengan perangkat, infrastruktur, dan sistem sudah berjalan."
8,9,"[doc_2, sent_58]",0.292297,0.660792,0.567525,"Sejalan dengan hal ini, prioritas investasi TI pun bergeser ke arah penerapan perangkay AI guna meningkatkan produktivitas dan mendukung proses inferensi AI secara lokal."
9,10,"[doc_2, sent_60]",0.291337,0.663600,0.577276,"Artinya, perangkat tersebut memiliki kemampuan dan kinerja yang diperlukan untuk menjalankan model AI secara lokal di sisi edge ."
10,11,"[doc_2, sent_31]",0.285604,0.678678,0.631570,"Melalui riset ini, Lenovo memetakan kesiapan, kapabilitas, dan prioritas perubahan dalam mengadipsi AI di lingkungan bisnis."
11,12,"[doc_2, sent_1]",0.277077,0.639850,0.569392,Adopsi kecerdasan buatan (AI) di kawasan ASEAN terus menunjukkan tren positif.
12,13,"[doc_1, sent_22]",0.275358,0.662709,0.628462,Mereka adalah kontributor strategis yang turut menentukan arah teknologi masa depan yang lebih beretika dan berorientasi pada kepentingan manusia.
13,14,"[doc_1, sent_4]",0.273084,0.617614,0.530818,"Baginya, kunci utama efektivitas AI terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat."
14,15,"[doc_1, sent_12]",0.268760,0.617771,0.545599,"Ia mengibaratkan data sebagai kompas untuk optimasi efisiensi dan akurasi, namun terobosan besar tetap membutuhkan visi manusia."
15,16,"[doc_2, sent_13]",0.261964,0.584686,0.491054,"Jadi hybrid AI itu bukan pilihan, tapi itu sudah keharusan bagi perusahaan-perusahaan yang di ASEAN, ujarBudi Janto, di Jakarta, baru-baru ini."
16,17,"[doc_1, sent_3]",0.260887,0.636507,0.615560,"Dalam webinar bertajuk AI Streamline Your Business: Build Internal Apps with AI baru-baru ini, Juan membedah peta jalan pengembangan AI yang melampaui sekadar kecanggihan teknis."
17,18,"[doc_2, sent_43]",0.256634,0.649618,0.660327,"Pada 2026 fokus AI didominasi oleh pendekatan berbasis hasil (outcome-based), yang mengisi tiga posisi teratas dalam strategi perusahaan."
18,19,"[doc_3, sent_19]",0.254324,0.583649,0.514102,"Fitur-fitur ini mencakup ""Produktivitas Sekali Ketuk"" untuk membantu pengguna membuat daftar tugas, catatan, dan menjalankan perintah kerja ringan dengan cepat."
19,20,"[doc_3, sent_36]",0.254086,0.613007,0.583394,"Infinix Smart 10 Plus hadir dengan pengalaman kecerdasan buatan (AI) yang menonjol, salah satu daya tariknya terletak pada kehadiran Folax, asisten virtual berbasis AI."
20,21,"[doc_2, sent_23]",0.252846,0.606517,0.572384,Berkat kelincahan dan kematangan tata kelola di kawasan ASEAN menjadikannya sebagai lingkungan uji coba yang ideal untuk Agentic AI.
21,22,"[doc_2, sent_14]",0.251351,0.622286,0.614163,"Seiring dengan hal itu, fokus perusahaan di ASEAN+ mulai beralih ke Agentic AI."
22,23,"[doc_2, sent_54]",0.247365,0.546647,0.450959,"Penerapan AI Hybrid turut dipengaruhi oleh tingginya biaya pengelolaan data di cloud, serta kekhawatiran terkait keamanan dan privasi data."
23,24,"[doc_2, sent_39]",0.247167,0.609560,0.598417,Prioritas kedua adalah reinvensi bisnis berbasis AI.
24,25,"[doc_1, sent_2]",0.242977,0.603104,0.597320,"Product Manager di Google Amerika Serikat, Juan Anugraha Djuwadi, kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi AI dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global."
25,26,"[doc_2, sent_20]",0.241825,0.632195,0.669040,Kesenjangan kesiapan ini rupanya masih menunjukkan adanya tantangan mendasar dalam penerapan AI.
26,27,"[doc_1, sent_20]",0.237592,0.573549,0.546308,"Ia memperkirakan lahirnya erasoftware on-the-fly, di mana perangkat lunak dihasilkan secarareal-timesesuai kebutuhan instan pengguna, baik melalui antarmuka teks maupun suara."
27,28,"[doc_1, sent_8]",0.231531,0.547988,0.506869,"Prinsip ini diterjemahkan ke dalam dua filosofi kunci:less is moredanthe details matter.Menurutnya, dalam skala pengguna miliaran seperti di Google, detail sekecil apa pun menjadi isu strategis."
28,29,"[doc_1, sent_13]",0.231066,0.570823,0.561701,"Data memvalidasi masa kini, namun intuisi mendefinisikan masa depan, ungkapnya."
29,30,"[doc_2, sent_52]",0.231024,0.607128,0.646552,"Beberapa diantaranya yaitu: Jika melihat keseluruhan faktor tersebut, inilah alasan mengapa terjadi pergeseran menuju penerapan AI berbasis hibrida."
30,31,"[doc_2, sent_49]",0.229875,0.552301,0.522452,"Adopsi AI tidak lagi terbatas pada fungsi IT seperti analitik data, keamanan siber dan pengembangan perangkat lunak, tetapi juga mengarah ke fungsi non-IT."
31,32,"[doc_1, sent_18]",0.227890,0.578128,0.589334,Inovasi AI yang sukses di wilayah dengan keberagaman sosial tinggi seperti Indonesia dan APAC haruslah bersifat kontekstual dan berbasis pada kepercayaan.
32,33,"[doc_3, sent_11]",0.227472,0.493668,0.393653,com/ Agustin Setyo Wardani) Redmi 14 C tampil dengan peningkatan signifikan pada sektor kamera berkat dukungan kamera utama 50 MP dan teknologi AI.
33,34,"[doc_2, sent_2]",0.219458,0.605603,0.681546,Data terbaru yang terungkap dalam konferensi pers Lenovo Tech Day 2026 menunjukkan 67 persen organisasi di kawasan ASEAN+ sudah melakukan uji coba AI secara sistematis.
34,35,"[doc_2, sent_26]",0.218014,0.489132,0.414592,"Di sisi lain, Lenovoresmi Lenovo Tech Day 2026 dengan tema The Race for Enterprise AI."
35,36,"[doc_2, sent_24]",0.217247,0.531107,0.515093,yang terus berkembang.
36,37,"[doc_2, sent_50]",0.212403,0.533466,0.536744,"Di internal Lenovo sendiri, kami telah memanfaatkan AI dalam rantai pasok dan perencanaan logistik, ujar Thomas."
37,38,"[doc_2, sent_46]",0.211817,0.531519,0.534154,"Kini, perusahaan tidak hanya melihat pengembalian investasi secara langsung dari AI, tetapi juga peningkatan layanan pelanggan, keterlibatan karyawan yang lebih tinggi, serta pengambilan keputusan yang semakin baik, terang Thomas."
38,39,"[doc_2, sent_41]",0.211441,0.560991,0.604176,"Model AI kini dibawa langsung ke lingkungan kerja, sehingga karyawan dituntut mampu memahami dan mengintegrasikan proses berbasis AI ke dalam aktivitas sehari-hari."
39,40,"[doc_2, sent_25]",0.210440,0.488474,0.438306,"Pemenangnya di eraagentic A Ibukan yang paling cepat bergerak, tapi mereka bilang yang paling dapat dipercaya, dan paling dapat tata kelolanya baik, tegas Budi."
40,41,"[doc_2, sent_35]",0.207881,0.571542,0.640659,"Namun kini, prioritas bisnis telah bergeser ke bagaimana AI mampu mendorong peningkatan pendapatan dan profitabilitas, ujar Thomas."
41,42,"[doc_1, sent_5]",0.206632,0.516686,0.516828,"Juan, yang merupakan alumnus Columbia University, menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi."
42,43,"[doc_3, sent_4]",0.205712,0.595791,0.704473,Beragam pembuat ponsel kini berlomba-lomba memasukkan AI ke model H Pentry-leveldan menengah buatan mereka masing-masing.
43,44,"[doc_2, sent_27]",0.204982,0.526021,0.544109,Forum ini menjadi panggung perusahaan asal China tersebut untuk memaparkan arah perkembangan adopsikecerdasan buatan(AI) di sektor perusahaan.
44,45,"[doc_3, sent_31]",0.200384,0.506059,0.512859,"(Dok: Vivo) Vivo Y 19 s Pro dilengkapi beragam fitur AI yang memudahkan pengguna mengolah foto, menjadikannya pilihan menarik bagi penggemar fotografi."
45,46,"[doc_2, sent_57]",0.197426,0.597040,0.735005,Sehingga pendekatan hybrid menjadi standar baru dalam penerapan AI di lingkungan perusahaan.
46,47,"[doc_3, sent_6]",0.197365,0.521198,0.558247,"Mengawali tahun 2026, tren HP AI dengan harga terjangkau akan semakin kuat."
47,48,"[doc_2, sent_19]",0.193090,0.507398,0.540294,"11 persen ini yang bilang bahwa dia siap untuk melakukan skalanyaagency AI, ungkap Budi."
48,49,"[doc_2, sent_15]",0.192998,0.545932,0.630516,Tercatat peningkatan fokus pada Agentic AI mencapai 91 persen secara tahunan (year on year).
49,50,"[doc_2, sent_7]",0.192702,0.485786,0.491163,"Sejumlah sektor tercatat menjadi pionir dalam penerapan AI, di antaranya telekomunikasi, layanan kesehatan, dan pemerintah."
50,51,"[doc_3, sent_5]",0.191325,0.575667,0.705474,"Tujuannya jelas, untuk membantu produktivitas, memoles foti, dan permudah aktivitas harian."
51,52,"[doc_3, sent_30]",0.191083,0.461529,0.439957,Tampilan Vivo Y 19 s yang resmi meluncur untuk pasar Indonesia.
52,53,"[doc_3, sent_17]",0.190131,0.539838,0.625851,"Infinix HOT 60 i Infinix HOT 60 i hadir dengan serangkaian fitur kecerdasan buatan (AI) yang diklaim paling lengkap di kelasnya, menjadikannya pilihan menarik di segmen harga terjangkau."
53,54,"[doc_3, sent_35]",0.188391,0.490535,0.516614,"Potret HP Infinix Smart 10 Plus, HP Rp 1 jutaan terbaru yang hadir dengan dukungan AI hingga sertifikat anti debu dan air, IP 64 (Foto: Infinix)."
54,55,"[doc_2, sent_53]",0.184668,0.597593,0.778824,"Saat ini, hampir 90 persen organisasi menyatakan lebih memilih atau tengah beralih ke model penerapan AI hibrida, ungkap Thomas."
55,56,"[doc_1, sent_1]",0.183526,0.556876,0.687626,"Di tengah perlombaan global mengadopsi kecerdasan buatan (AI), talenta Indonesia mulai mengambil peran krusial di pusat inovasi dunia."
56,57,"[doc_2, sent_42]",0.182649,0.511243,0.584070,"Sementara itu, prioritas ketiga adalah peningkatan pengalaman dan kepuasan."

In [ ]:

final_text_parts = []

for item in selected_data:
    final_text_parts.append(item['text'])

extractive_clean = " ".join(final_text_parts)

print("\n Hasil Ekstraktif:")
print("-" * 75)
print(extractive_clean)
print("-" * 75)

inp_model = " ".join(extractive_clean.split()[:512])
print(f"\n Input ke Model Abstractive Siap.")
print(f"   Jumlah Kata: {len(inp_model.split())}")

 Hasil Ekstraktif:
---------------------------------------------------------------------------
Dalam skala yang lebih luas, Lenovo mengidentifikasi sejumlah faktor kunci keberhasilan penerapan AI. Perusahaan mulai mencari cara agar teknologi ini benar-benar berdampak bagi bisnis. Tren kecerdasan buatan (AI) semakin merambah ke segmensmartphone entry-leveldan menengah. Perangkat-perangkat yang kini dibawa Lenovo ke pasar telah memiliki kapabilitas AI. Jika AS sudah mapan dalam hal monetisasi perangkat lunak, Indonesia masih berada dalam tahap transisi yang dinamis. Dari 2025 ke 2026, tahap implementasi dan uji coba AI meningkat menjadi 66 persen. Pendekatan ini menjadi krusial bagi para regulator dan pemimpin perusahaan di Asia Pasifik (APAC) agar tidak hanya bersikap reaktif terhadap tren, tetapi mampu menjadi visioner dalam merancang ekosistem digital. Bukan lagi soal membangun model AI, tetapi bagaimana mengintegrasikannya dengan perangkat, infrastruktur, dan sistem sudah berjalan. Sejalan dengan hal ini, prioritas investasi TI pun bergeser ke arah penerapan perangkay AI guna meningkatkan produktivitas dan mendukung proses inferensi AI secara lokal. Artinya, perangkat tersebut memiliki kemampuan dan kinerja yang diperlukan untuk menjalankan model AI secara lokal di sisi edge . Melalui riset ini, Lenovo memetakan kesiapan, kapabilitas, dan prioritas perubahan dalam mengadipsi AI di lingkungan bisnis. Adopsi kecerdasan buatan (AI) di kawasan ASEAN terus menunjukkan tren positif. Mereka adalah kontributor strategis yang turut menentukan arah teknologi masa depan yang lebih beretika dan berorientasi pada kepentingan manusia. Baginya, kunci utama efektivitas AI terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat. Ia mengibaratkan data sebagai kompas untuk optimasi efisiensi dan akurasi, namun terobosan besar tetap membutuhkan visi manusia. Jadi hybrid AI itu bukan pilihan, tapi itu sudah keharusan bagi perusahaan-perusahaan yang di ASEAN, ujarBudi Janto, di Jakarta, baru-baru ini. Dalam webinar bertajuk AI Streamline Your Business: Build Internal Apps with AI baru-baru ini, Juan membedah peta jalan pengembangan AI yang melampaui sekadar kecanggihan teknis. Pada 2026 fokus AI didominasi oleh pendekatan berbasis hasil (outcome-based), yang mengisi tiga posisi teratas dalam strategi perusahaan. Fitur-fitur ini mencakup "Produktivitas Sekali Ketuk" untuk membantu pengguna membuat daftar tugas, catatan, dan menjalankan perintah kerja ringan dengan cepat. Infinix Smart 10 Plus hadir dengan pengalaman kecerdasan buatan (AI) yang menonjol, salah satu daya tariknya terletak pada kehadiran Folax, asisten virtual berbasis AI. Berkat kelincahan dan kematangan tata kelola di kawasan ASEAN menjadikannya sebagai lingkungan uji coba yang ideal untuk Agentic AI. Seiring dengan hal itu, fokus perusahaan di ASEAN+ mulai beralih ke Agentic AI. Penerapan AI Hybrid turut dipengaruhi oleh tingginya biaya pengelolaan data di cloud, serta kekhawatiran terkait keamanan dan privasi data. Prioritas kedua adalah reinvensi bisnis berbasis AI. Product Manager di Google Amerika Serikat, Juan Anugraha Djuwadi, kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi AI dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global. Kesenjangan kesiapan ini rupanya masih menunjukkan adanya tantangan mendasar dalam penerapan AI. Ia memperkirakan lahirnya erasoftware on-the-fly, di mana perangkat lunak dihasilkan secarareal-timesesuai kebutuhan instan pengguna, baik melalui antarmuka teks maupun suara. Prinsip ini diterjemahkan ke dalam dua filosofi kunci:less is moredanthe details matter.Menurutnya, dalam skala pengguna miliaran seperti di Google, detail sekecil apa pun menjadi isu strategis. Data memvalidasi masa kini, namun intuisi mendefinisikan masa depan, ungkapnya. Beberapa diantaranya yaitu: Jika melihat keseluruhan faktor tersebut, inilah alasan mengapa terjadi pergeseran menuju penerapan AI berbasis hibrida. Adopsi AI tidak lagi terbatas pada fungsi IT seperti analitik data, keamanan siber dan pengembangan perangkat lunak, tetapi juga mengarah ke fungsi non-IT. Inovasi AI yang sukses di wilayah dengan keberagaman sosial tinggi seperti Indonesia dan APAC haruslah bersifat kontekstual dan berbasis pada kepercayaan. com/ Agustin Setyo Wardani) Redmi 14 C tampil dengan peningkatan signifikan pada sektor kamera berkat dukungan kamera utama 50 MP dan teknologi AI. Data terbaru yang terungkap dalam konferensi pers Lenovo Tech Day 2026 menunjukkan 67 persen organisasi di kawasan ASEAN+ sudah melakukan uji coba AI secara sistematis. Di sisi lain, Lenovoresmi Lenovo Tech Day 2026 dengan tema The Race for Enterprise AI. yang terus berkembang. Di internal Lenovo sendiri, kami telah memanfaatkan AI dalam rantai pasok dan perencanaan logistik, ujar Thomas. Kini, perusahaan tidak hanya melihat pengembalian investasi secara langsung dari AI, tetapi juga peningkatan layanan pelanggan, keterlibatan karyawan yang lebih tinggi, serta pengambilan keputusan yang semakin baik, terang Thomas. Model AI kini dibawa langsung ke lingkungan kerja, sehingga karyawan dituntut mampu memahami dan mengintegrasikan proses berbasis AI ke dalam aktivitas sehari-hari. Pemenangnya di eraagentic A Ibukan yang paling cepat bergerak, tapi mereka bilang yang paling dapat dipercaya, dan paling dapat tata kelolanya baik, tegas Budi. Namun kini, prioritas bisnis telah bergeser ke bagaimana AI mampu mendorong peningkatan pendapatan dan profitabilitas, ujar Thomas. Juan, yang merupakan alumnus Columbia University, menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi. Beragam pembuat ponsel kini berlomba-lomba memasukkan AI ke model H Pentry-leveldan menengah buatan mereka masing-masing. Forum ini menjadi panggung perusahaan asal China tersebut untuk memaparkan arah perkembangan adopsikecerdasan buatan(AI) di sektor perusahaan. (Dok: Vivo) Vivo Y 19 s Pro dilengkapi beragam fitur AI yang memudahkan pengguna mengolah foto, menjadikannya pilihan menarik bagi penggemar fotografi. Sehingga pendekatan hybrid menjadi standar baru dalam penerapan AI di lingkungan perusahaan. Mengawali tahun 2026, tren HP AI dengan harga terjangkau akan semakin kuat. 11 persen ini yang bilang bahwa dia siap untuk melakukan skalanyaagency AI, ungkap Budi. Tercatat peningkatan fokus pada Agentic AI mencapai 91 persen secara tahunan (year on year). Sejumlah sektor tercatat menjadi pionir dalam penerapan AI, di antaranya telekomunikasi, layanan kesehatan, dan pemerintah. Tujuannya jelas, untuk membantu produktivitas, memoles foti, dan permudah aktivitas harian. Tampilan Vivo Y 19 s yang resmi meluncur untuk pasar Indonesia. Infinix HOT 60 i Infinix HOT 60 i hadir dengan serangkaian fitur kecerdasan buatan (AI) yang diklaim paling lengkap di kelasnya, menjadikannya pilihan menarik di segmen harga terjangkau. Potret HP Infinix Smart 10 Plus, HP Rp 1 jutaan terbaru yang hadir dengan dukungan AI hingga sertifikat anti debu dan air, IP 64 (Foto: Infinix). Saat ini, hampir 90 persen organisasi menyatakan lebih memilih atau tengah beralih ke model penerapan AI hibrida, ungkap Thomas. Di tengah perlombaan global mengadopsi kecerdasan buatan (AI), talenta Indonesia mulai mengambil peran krusial di pusat inovasi dunia. Sementara itu, prioritas ketiga adalah peningkatan pengalaman dan kepuasan.
---------------------------------------------------------------------------

 Input ke Model Abstractive Siap.
   Jumlah Kata: 512

In [ ]:
!pip install rouge_score

Requirement already satisfied: rouge_score in /usr/local/lib/python3.12/dist-packages (0.1.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.3)

In [ ]:


import pandas as pd
from rouge_score import rouge_scorer


ground_truth_text_1 = """
Di tengah perlombaan global mengadopsi kecerdasan buatan (AI), talenta Indonesia mulai mengambil peran krusial di pusat inovasi dunia. Product Manager di Google Amerika Serikat, Juan Anugraha Djuwadi, kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi AI dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global. Dalam webinar bertajuk “AI Streamline Your Business: Build Internal Apps with AI” baru-baru ini, Juan membedah peta jalan pengembangan AI yang melampaui sekadar kecanggihan teknis. Baginya, kunci utama efektivitas AI terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat. Juan, yang merupakan alumnus Columbia University, menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi. “Pengguna tidak peduli seberapa canggih teknologi di belakang layar. Mereka peduli apakah solusi itu berguna dan menyelesaikan masalah nyata,” ujar Juan, dikutip Kamis (15/1/2026). Prinsip ini diterjemahkan ke dalam dua filosofi kunci: “less is more” dan “the details matter.” Menurutnya, dalam skala pengguna miliaran seperti di Google, detail sekecil apa pun menjadi isu strategis. Kegagalan sistem sebesar satu persen saja dapat berdampak pada jutaan orang. Persfektif ini dinilai sangat relevan bagi pemerintah Indonesia dan perusahaan BUMN yang tengah mengintegrasikan AI dalam layanan publik berskala nasional. Terkait proses pengambilan keputusan, Juan menawarkan pendekatan moderat antara data dan intuisi. Ia mengibaratkan data sebagai kompas untuk optimasi efisiensi dan akurasi, namun terobosan besar tetap membutuhkan visi manusia. “Data memvalidasi masa kini, namun intuisi mendefinisikan masa depan,” ungkapnya. Pendekatan ini menjadi krusial bagi para regulator dan pemimpin perusahaan di Asia Pasifik (APAC) agar tidak hanya bersikap reaktif terhadap tren, tetapi mampu menjadi visioner dalam merancang ekosistem digital. Menyoroti lanskap digital di Tanah Air, Juan melihat adanya perbedaan fase kematangan antara pasar Amerika Serikat (AS) dan Indonesia. Jika AS sudah mapan dalam hal monetisasi perangkat lunak, Indonesia masih berada dalam tahap transisi yang dinamis. Ia memprediksi, seiring berkembangnya ekosistem digital di Indonesia, isu mengenai privasi data, etika AI, dan akuntabilitas akan menjadi agenda utama yang tak terelakkan. Inovasi AI yang sukses di wilayah dengan keberagaman sosial tinggi seperti Indonesia dan APAC haruslah bersifat kontekstual dan berbasis pada kepercayaan. Mantan profesional di Niantic dan Activision ini juga memproyeksikan pergeseran fundamental dalam lima tahun mendatang melalui demokratisasi AI. Ia memperkirakan lahirnya era “software on-the-fly”, di mana perangkat lunak dihasilkan secara real-time sesuai kebutuhan instan pengguna, baik melalui antarmuka teks maupun suara. Ia membuktikan bahwa peran talenta Indonesia bukan sekadar pelengkap, melainkan kontributor strategis yang turut menentukan arah teknologi masa depan yang beretika dan berorientasi pada kepentingan manusia.
""".strip()

ground_truth_text_2 = """
""".strip()

if 'selected_data' in globals() and selected_data:
    system_summary_text = " ".join([item['text'] for item in selected_data])
else:
    print("WARNING: Variable 'selected_data' kosong/tidak ditemukan.")

if system_summary_text and ground_truth_text_1:
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

    scores = scorer.score(ground_truth_text_1, system_summary_text)

    print("\n" + "="*60)
    print("HASIL EVALUASI AKHIR (ROUGE SCORE)")
    print(f"Lambda = {mmr.lambda_param}")
    print("="*60)

    print(f"\n SYSTEM SUMMARY (MMR):\n{system_summary_text}")
    print("-" * 60)
    print(f" GROUND TRUTH (Dari Annotator):\n{ground_truth_text_1}")
    print("-" * 60)

    results_data = {
        "Metric": ["ROUGE-1 (Kata)", "ROUGE-2 (Frasa)", "ROUGE-L (Urutan)"],
        "Precision": [scores['rouge1'].precision, scores['rouge2'].precision, scores['rougeL'].precision],
        "Recall": [scores['rouge1'].recall, scores['rouge2'].recall, scores['rougeL'].recall],
        "F1-Score": [scores['rouge1'].fmeasure, scores['rouge2'].fmeasure, scores['rougeL'].fmeasure]
    }

    df_results = pd.DataFrame(results_data)

    print("\nTABEL SKOR:")
    display(df_results.style.format("{:.4f}", subset=["Precision", "Recall", "F1-Score"]))

    f1_r1 = scores['rouge1'].fmeasure
    f1_r2 = scores['rouge2'].fmeasure
    f1_rl = scores['rougeL'].fmeasure
else:
    print(" Evaluasi dibatalkan karena data kosong.")

============================================================
HASIL EVALUASI AKHIR (ROUGE SCORE)
Lambda = 0.7
============================================================

 SYSTEM SUMMARY (MMR):
Dalam skala yang lebih luas, Lenovo mengidentifikasi sejumlah faktor kunci keberhasilan penerapan AI. Perusahaan mulai mencari cara agar teknologi ini benar-benar berdampak bagi bisnis. Tren kecerdasan buatan (AI) semakin merambah ke segmensmartphone entry-leveldan menengah. Perangkat-perangkat yang kini dibawa Lenovo ke pasar telah memiliki kapabilitas AI. Jika AS sudah mapan dalam hal monetisasi perangkat lunak, Indonesia masih berada dalam tahap transisi yang dinamis. Dari 2025 ke 2026, tahap implementasi dan uji coba AI meningkat menjadi 66 persen. Pendekatan ini menjadi krusial bagi para regulator dan pemimpin perusahaan di Asia Pasifik (APAC) agar tidak hanya bersikap reaktif terhadap tren, tetapi mampu menjadi visioner dalam merancang ekosistem digital. Bukan lagi soal membangun model AI, tetapi bagaimana mengintegrasikannya dengan perangkat, infrastruktur, dan sistem sudah berjalan. Sejalan dengan hal ini, prioritas investasi TI pun bergeser ke arah penerapan perangkay AI guna meningkatkan produktivitas dan mendukung proses inferensi AI secara lokal. Artinya, perangkat tersebut memiliki kemampuan dan kinerja yang diperlukan untuk menjalankan model AI secara lokal di sisi edge . Melalui riset ini, Lenovo memetakan kesiapan, kapabilitas, dan prioritas perubahan dalam mengadipsi AI di lingkungan bisnis. Adopsi kecerdasan buatan (AI) di kawasan ASEAN terus menunjukkan tren positif. Mereka adalah kontributor strategis yang turut menentukan arah teknologi masa depan yang lebih beretika dan berorientasi pada kepentingan manusia. Baginya, kunci utama efektivitas AI terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat. Ia mengibaratkan data sebagai kompas untuk optimasi efisiensi dan akurasi, namun terobosan besar tetap membutuhkan visi manusia. Jadi hybrid AI itu bukan pilihan, tapi itu sudah keharusan bagi perusahaan-perusahaan yang di ASEAN, ujarBudi Janto, di Jakarta, baru-baru ini. Dalam webinar bertajuk AI Streamline Your Business: Build Internal Apps with AI baru-baru ini, Juan membedah peta jalan pengembangan AI yang melampaui sekadar kecanggihan teknis. Pada 2026 fokus AI didominasi oleh pendekatan berbasis hasil (outcome-based), yang mengisi tiga posisi teratas dalam strategi perusahaan. Fitur-fitur ini mencakup "Produktivitas Sekali Ketuk" untuk membantu pengguna membuat daftar tugas, catatan, dan menjalankan perintah kerja ringan dengan cepat. Infinix Smart 10 Plus hadir dengan pengalaman kecerdasan buatan (AI) yang menonjol, salah satu daya tariknya terletak pada kehadiran Folax, asisten virtual berbasis AI. Berkat kelincahan dan kematangan tata kelola di kawasan ASEAN menjadikannya sebagai lingkungan uji coba yang ideal untuk Agentic AI. Seiring dengan hal itu, fokus perusahaan di ASEAN+ mulai beralih ke Agentic AI. Penerapan AI Hybrid turut dipengaruhi oleh tingginya biaya pengelolaan data di cloud, serta kekhawatiran terkait keamanan dan privasi data. Prioritas kedua adalah reinvensi bisnis berbasis AI. Product Manager di Google Amerika Serikat, Juan Anugraha Djuwadi, kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi AI dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global. Kesenjangan kesiapan ini rupanya masih menunjukkan adanya tantangan mendasar dalam penerapan AI. Ia memperkirakan lahirnya erasoftware on-the-fly, di mana perangkat lunak dihasilkan secarareal-timesesuai kebutuhan instan pengguna, baik melalui antarmuka teks maupun suara. Prinsip ini diterjemahkan ke dalam dua filosofi kunci:less is moredanthe details matter.Menurutnya, dalam skala pengguna miliaran seperti di Google, detail sekecil apa pun menjadi isu strategis. Data memvalidasi masa kini, namun intuisi mendefinisikan masa depan, ungkapnya. Beberapa diantaranya yaitu: Jika melihat keseluruhan faktor tersebut, inilah alasan mengapa terjadi pergeseran menuju penerapan AI berbasis hibrida. Adopsi AI tidak lagi terbatas pada fungsi IT seperti analitik data, keamanan siber dan pengembangan perangkat lunak, tetapi juga mengarah ke fungsi non-IT. Inovasi AI yang sukses di wilayah dengan keberagaman sosial tinggi seperti Indonesia dan APAC haruslah bersifat kontekstual dan berbasis pada kepercayaan. com/ Agustin Setyo Wardani) Redmi 14 C tampil dengan peningkatan signifikan pada sektor kamera berkat dukungan kamera utama 50 MP dan teknologi AI. Data terbaru yang terungkap dalam konferensi pers Lenovo Tech Day 2026 menunjukkan 67 persen organisasi di kawasan ASEAN+ sudah melakukan uji coba AI secara sistematis. Di sisi lain, Lenovoresmi Lenovo Tech Day 2026 dengan tema The Race for Enterprise AI. yang terus berkembang. Di internal Lenovo sendiri, kami telah memanfaatkan AI dalam rantai pasok dan perencanaan logistik, ujar Thomas. Kini, perusahaan tidak hanya melihat pengembalian investasi secara langsung dari AI, tetapi juga peningkatan layanan pelanggan, keterlibatan karyawan yang lebih tinggi, serta pengambilan keputusan yang semakin baik, terang Thomas. Model AI kini dibawa langsung ke lingkungan kerja, sehingga karyawan dituntut mampu memahami dan mengintegrasikan proses berbasis AI ke dalam aktivitas sehari-hari. Pemenangnya di eraagentic A Ibukan yang paling cepat bergerak, tapi mereka bilang yang paling dapat dipercaya, dan paling dapat tata kelolanya baik, tegas Budi. Namun kini, prioritas bisnis telah bergeser ke bagaimana AI mampu mendorong peningkatan pendapatan dan profitabilitas, ujar Thomas. Juan, yang merupakan alumnus Columbia University, menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi. Beragam pembuat ponsel kini berlomba-lomba memasukkan AI ke model H Pentry-leveldan menengah buatan mereka masing-masing. Forum ini menjadi panggung perusahaan asal China tersebut untuk memaparkan arah perkembangan adopsikecerdasan buatan(AI) di sektor perusahaan. (Dok: Vivo) Vivo Y 19 s Pro dilengkapi beragam fitur AI yang memudahkan pengguna mengolah foto, menjadikannya pilihan menarik bagi penggemar fotografi. Sehingga pendekatan hybrid menjadi standar baru dalam penerapan AI di lingkungan perusahaan. Mengawali tahun 2026, tren HP AI dengan harga terjangkau akan semakin kuat. 11 persen ini yang bilang bahwa dia siap untuk melakukan skalanyaagency AI, ungkap Budi. Tercatat peningkatan fokus pada Agentic AI mencapai 91 persen secara tahunan (year on year). Sejumlah sektor tercatat menjadi pionir dalam penerapan AI, di antaranya telekomunikasi, layanan kesehatan, dan pemerintah. Tujuannya jelas, untuk membantu produktivitas, memoles foti, dan permudah aktivitas harian. Tampilan Vivo Y 19 s yang resmi meluncur untuk pasar Indonesia. Infinix HOT 60 i Infinix HOT 60 i hadir dengan serangkaian fitur kecerdasan buatan (AI) yang diklaim paling lengkap di kelasnya, menjadikannya pilihan menarik di segmen harga terjangkau. Potret HP Infinix Smart 10 Plus, HP Rp 1 jutaan terbaru yang hadir dengan dukungan AI hingga sertifikat anti debu dan air, IP 64 (Foto: Infinix). Saat ini, hampir 90 persen organisasi menyatakan lebih memilih atau tengah beralih ke model penerapan AI hibrida, ungkap Thomas. Di tengah perlombaan global mengadopsi kecerdasan buatan (AI), talenta Indonesia mulai mengambil peran krusial di pusat inovasi dunia. Sementara itu, prioritas ketiga adalah peningkatan pengalaman dan kepuasan.
------------------------------------------------------------
 GROUND TRUTH (Dari Annotator):
Di tengah perlombaan global mengadopsi kecerdasan buatan (AI), talenta Indonesia mulai mengambil peran krusial di pusat inovasi dunia. Product Manager di Google Amerika Serikat, Juan Anugraha Djuwadi, kini menjadi salah satu aktor strategis yang mengarahkan bagaimana teknologi AI dikembangkan agar tetap manusiawi dan berdampak luas bagi pengguna global. Dalam webinar bertajuk “AI Streamline Your Business: Build Internal Apps with AI” baru-baru ini, Juan membedah peta jalan pengembangan AI yang melampaui sekadar kecanggihan teknis. Baginya, kunci utama efektivitas AI terletak pada kegunaannya dalam menjawab persoalan nyata di masyarakat. Juan, yang merupakan alumnus Columbia University, menegaskan bahwa pengguna akhir seringkali tidak mempedulikan kerumitan algoritma di balik sebuah aplikasi. “Pengguna tidak peduli seberapa canggih teknologi di belakang layar. Mereka peduli apakah solusi itu berguna dan menyelesaikan masalah nyata,” ujar Juan, dikutip Kamis (15/1/2026). Prinsip ini diterjemahkan ke dalam dua filosofi kunci: “less is more” dan “the details matter.” Menurutnya, dalam skala pengguna miliaran seperti di Google, detail sekecil apa pun menjadi isu strategis. Kegagalan sistem sebesar satu persen saja dapat berdampak pada jutaan orang. Persfektif ini dinilai sangat relevan bagi pemerintah Indonesia dan perusahaan BUMN yang tengah mengintegrasikan AI dalam layanan publik berskala nasional. Terkait proses pengambilan keputusan, Juan menawarkan pendekatan moderat antara data dan intuisi. Ia mengibaratkan data sebagai kompas untuk optimasi efisiensi dan akurasi, namun terobosan besar tetap membutuhkan visi manusia. “Data memvalidasi masa kini, namun intuisi mendefinisikan masa depan,” ungkapnya. Pendekatan ini menjadi krusial bagi para regulator dan pemimpin perusahaan di Asia Pasifik (APAC) agar tidak hanya bersikap reaktif terhadap tren, tetapi mampu menjadi visioner dalam merancang ekosistem digital. Menyoroti lanskap digital di Tanah Air, Juan melihat adanya perbedaan fase kematangan antara pasar Amerika Serikat (AS) dan Indonesia. Jika AS sudah mapan dalam hal monetisasi perangkat lunak, Indonesia masih berada dalam tahap transisi yang dinamis. Ia memprediksi, seiring berkembangnya ekosistem digital di Indonesia, isu mengenai privasi data, etika AI, dan akuntabilitas akan menjadi agenda utama yang tak terelakkan. Inovasi AI yang sukses di wilayah dengan keberagaman sosial tinggi seperti Indonesia dan APAC haruslah bersifat kontekstual dan berbasis pada kepercayaan. Mantan profesional di Niantic dan Activision ini juga memproyeksikan pergeseran fundamental dalam lima tahun mendatang melalui demokratisasi AI. Ia memperkirakan lahirnya era “software on-the-fly”, di mana perangkat lunak dihasilkan secara real-time sesuai kebutuhan instan pengguna, baik melalui antarmuka teks maupun suara. Ia membuktikan bahwa peran talenta Indonesia bukan sekadar pelengkap, melainkan kontributor strategis yang turut menentukan arah teknologi masa depan yang beretika dan berorientasi pada kepentingan manusia.
------------------------------------------------------------

TABEL SKOR: